### ISSUE TITLE
Memory usage issue cause dns stuck

### ISSUE THREAD

**Issue by haosdent** [miekg/dns#732] opened 2018-08-30 09:44 UTC
In 

```
func (srv *Server) serveDNS(w *response) {
	req := new(Msg)
	err := req.Unpack(w.msg)
	if err != nil { // Send a FormatError back
		x := new(Msg)
		x.SetRcodeFormatError(req)
		w.WriteMsg(x)
		return
	}
	if !srv.Unsafe && req.Response {
		return
	}
```

Every dns request would create a new dns msg object, this make DNS library occupy a lot of memory. Is it OK to change it use `sync.Pool`?

**Comment by larytet** [comment] 2018-09-04 13:51
I am profiling the DNS server. The server is a consistent top usage of the memory. For example, under 1K queries/s I git 
```
(pprof) top50
Showing nodes accounting for 33606.54kB, 100% of 33606.54kB total
      flat  flat%   sum%        cum   cum%
31045.99kB 92.38% 92.38% 31045.99kB 92.38%  dnsProxyWin/vendor/github.com/miekg/dns.(*Server).readUDP
 1024.38kB  3.05% 95.43%  1024.38kB  3.05%  runtime.malg
  512.06kB  1.52% 96.95% 31558.05kB 93.90%  dnsProxyWin/vendor/github.com/miekg/dns.(*Server).serveUDP
  512.06kB  1.52% 98.48%   512.06kB  1.52%  net/url.(*URL).String
  512.05kB  1.52%   100%   512.05kB  1.52%  net.(*netFD).connect
         0     0%   100% 31558.05kB 93.90%  dnsProxyWin/vendor/github.com/miekg/dns.(*Server).ListenAndServe
         0     0%   100%   512.06kB  1.52%  dnsProxyWin/vendor/github.com/miekg/dns.(*Server).serve
         0     0%   100%   512.06kB  1.52%  dnsProxyWin/vendor/github.com/miekg/dns.(*Server).serveDNS
         0     0%   100%   512.06kB  1.52%  dnsProxyWin/vendor/github.com/miekg/dns.(*Server).worker
         0     0%   100% 31045.99kB 92.38%  dnsProxyWin/vendor/github.com/miekg/dns.(*defaultReader).ReadUDP

```

**Comment by larytet** [comment] 2018-09-05 06:09
```
(pprof) top5
Showing nodes accounting for 22778.25kB, 100% of 22778.25kB total
Showing top 5 nodes out of 15
      flat  flat%   sum%        cum   cum%
21241.99kB 93.26% 93.26% 21754.02kB 95.50%  dnsProxyWin/vendor/github.com/miekg/dns.(*Server).readUDP
  512.19kB  2.25% 95.50%   512.19kB  2.25%  runtime.malg
  512.05kB  2.25% 97.75%   512.05kB  2.25%  net/http.(*Transport).dialConn
  512.02kB  2.25%   100%   512.02kB  2.25%  net.(*UDPConn).readMsg
         0     0%   100% 21754.02kB 95.50%  dnsProxyWin/vendor/github.com/miekg/dns.(*Server).ListenAndServe
(pprof) list readUDP
Total: 22.24MB
ROUTINE ======================== dnsProxyWin/vendor/github.com/miekg/dns.(*Server).readUDP in /home/arkady/go/src/dnsProxyWin/vendor/github.com/miekg/dns/server.go
   20.74MB    21.24MB (flat, cum) 95.50% of Total
         .          .    689:	return m, nil
         .          .    690:}
         .          .    691:
         .          .    692:func (srv *Server) readUDP(conn *net.UDPConn, timeout time.Duration) ([]byte, *SessionUDP, error) {
         .          .    693:	conn.SetReadDeadline(time.Now().Add(timeout))
   20.74MB    20.74MB    694:	m := make([]byte, srv.UDPSize)
         .   512.02kB    695:	n, s, err := ReadFromSessionUDP(conn, m)
         .          .    696:	if err != nil {
         .          .    697:		return nil, nil, err
         .          .    698:	}
         .          .    699:	m = m[:n]
         .          .    700:	return m, s, nil
(pprof) 

```

**Comment by larytet** [comment] 2018-09-05 06:47
512 bytes DNS seems to be a packet size when the memory consumption distribution is reasonably flat. I think I will change my naive implementation of the ServeDNS() with an asynchronous block free design.

**Comment by miekg** [comment] 2018-09-05 08:37
Maybe we can lower the initial udp buffer size? Not sure what we use now,
512 should be ok for most? Does 512 work with dynamic updates? Are there
other protocol extension that potentially require a larger buffer?

**Comment by larytet** [comment] 2018-09-05 08:44
The default value appears to be MinMsgSize (512). 
I have added call to debug.SetGCPercent() to collect the memory more aggressively

**Comment by miekg** [comment] 2018-09-05 08:46
That can't be made any smaller.

**Comment by tmthrgd** [comment] 2018-09-05 09:01
I don’t think that `new(Msg)` could be replaced with a `sync.Pool` safely, because it’s passed to the handler which doesn’t document any sort of non-owning property or lifetime of the `Msg` struct. Nothing says it’s invalid for the handler to keep the `Msg` after it’s returned.

It should be possible to add a per-`Server` `sync.Pool` to hold the message buffers, which might work well.

The `make` call in `(*Server).readUDP` could be replaced by `srv.udpPool.Get().([]byte)` and `if w.udp != nil { srv.udpPool.Put(w.msg) }` could be added in `(*Server).serveDNS` directly after `req.Unpack(w.msg)`.

I can take a shot at implementing that in a few days. (Sorry for any typos, I’m writing on a phone).

**Comment by larytet** [comment] 2018-09-05 09:14
I was thinking about using  a list of chunks which gets allocated from a pool. The problem, I think, boils down to how GC collects the memory. In the perfect world immediately after ```m = m[:n]``` GC would return most of the allocated memory to the OS (or an internal pool or whatever). In reality the slice allocated memory rarely (ever?) goes down.

**Comment by tmthrgd** [comment] 2018-09-05 09:33
@larytet Slicing `m` will never result in memory being freed, only when `m` (and the underlying memory) finally has no more references to it. That won’t happen until `serveDNS` returns because it’s pinned by `response`. Adding `w.msg = nil` immediately after `req.Unpack(w.msg)` may see the memory freed sooner though. A `sync.Pool` as I described seems the best way to minimise memory usage.

**Comment by miekg** [comment] 2018-09-05 09:47
I don't like adding code to make GC do what you want. It's highly like that
code won't age well with newer go versions

**Comment by larytet** [comment] 2018-09-05 09:53
Copy the data to a smaller slice triggered by lower utilization of the Rx buffer: 
```
	if 2*n < srv.UDPSize {
		m1 := make([]byte, n)
		Copy(m1, m)
		m = m1
	} else {
		m = m[:n]
	}

```

**Comment by miekg** [comment] 2018-09-05 19:46
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Memory usage issue ..." ]
>Copy the data to a smaller slice triggered by lower utilization of the Rx buffer:
>```
>	if 2*n < srv.UDPSize {
>		m1 := make([]byte, n)
>		Copy(m1, m)
>		m = m1
>	} else {
>		m = m[:n]
>	}
>
>```

So, to safe memory we are going to copy it twice?

**Comment by larytet** [comment] 2018-09-06 07:31
I am not suggesting to apply this patch. I was trying to prove the theory that the problem is GC related

**Comment by larytet** [comment] 2018-09-12 08:40
I confirm the improvement in the e875a31

**Comment by tmthrgd** [comment] 2018-11-26 08:02
I'm going to go ahead and close this. The original request "Every dns request would create a new dns msg object, this make DNS library occupy a lot of memory." hasn't actually been addressed, but I'm quite sure we can't make that change. #735 should have gotten most of the way to reducing memory usage anyway.

**Closed by tmthrgd** 2018-11-26 08:02 UTC
