### ISSUE TITLE
Build fails with go 1.7 and 1.8: msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)

### ISSUE THREAD

**Issue by xtaran** [miekg/dns#701] opened 2018-06-14 14:02 UTC
Using go 1.7 or go 1.8 on Debian Stable, building fails as follows:

```
github.com/miekg/dns
# github.com/miekg/dns
gocode/src/github.com/miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
gocode/src/github.com/miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding
```

In case go 1.7 and go 1.8 are no more supported, please mention that in the README.

**Comment by tmthrgd** [comment] 2018-06-14 14:44
This is a duplicate of both #686 and #687. You’ll have to upgrade to go 1.9 or 1.10.

I’m closing this, (but I can open a small pull-request to re-support go 1.8/1.7 if @miekg wanted).

**Closed by tmthrgd** 2018-06-14 14:44 UTC

**Comment by miekg** [comment] 2018-06-14 15:38
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Build fails with go..." ]
>This is a duplicate of both #686 and #687. You’ll have to upgrade to go 1.9 or 1.10.
>
>I’m closing this, (but I can open a small pull-request to re-support go 1.8/1.7 if @miekg wanted).

We committed to supporting the last 2 major releases, this opens the flood gates 
for supporting all Go version; I'm not in favor of burdening OSS devs with that 
extra work.

**Comment by andrewtj** [comment] 2018-06-15 03:39
> In case go 1.7 and go 1.8 are no more supported, please mention that in the README.

There is a support statement in the README.
