### ISSUE TITLE
cause panic when concurrent use Msg

### ISSUE THREAD

**Issue by Dreamacro** [miekg/dns#1094] opened 2020-03-23 03:16 UTC
PoC (run about 1min on macOS 10.15.2):
```go
package main

import (
	"fmt"
	"strings"
	"time"

	"github.com/miekg/dns"
)

func main() {
	msg := &dns.Msg{}
	msg.Question = []dns.Question{
		dns.Question{"example.com.", dns.TypeA, dns.ClassINET},
		dns.Question{"example2.com.", dns.TypeA, dns.ClassINET},
	}

	msg2 := &dns.Msg{}
	msg2.Question = make([]dns.Question, len(msg.Question))

	trimFunc := func() {
		for {
			time.Sleep(time.Millisecond)
			s := strings.TrimSuffix(msg2.Question[0].Name, ".")
			s = fmt.Sprintf("s %s", s)
		}
	}

	for i := 0; i < 20; i++ {
		go trimFunc()
	}

	for {
		time.Sleep(time.Millisecond * 10)
		msg.CopyTo(msg2)
	}
}
```

Possible root case:

https://github.com/miekg/dns/blob/f515aa579d28efa1af67d9a62cc57f2dfe59da76/msg.go#L1056-L1057

Inadequate Patch:

```go
questions := make([]Question, len(dns.Question))
copy(questions, dns.Question)
r1.Question = questions
```

**Comment by tmthrgd** [comment] 2020-03-23 05:11
The race condition isn't in the `CopyTo` method but in your example code. `CopyTo` changes the `msg2` you pass into it which *is* a race condition. You can't read from `msg2` (in `trimFunc`) and write to it (in `CopyTo`) at the same time without locks.

I'm not sure what your original problem actually is, but either stop calling `CopyTo` while `trimFunc` is running or move `msg2` and the copy into `trimFunc` entirely. (In your minimal example above, there's no need to create a copy at all).

I'm going to close this as it's not a bug in the library.

**Closed by tmthrgd** 2020-03-23 05:11 UTC
