### ISSUE TITLE
May be need a new function Join(labels ...string)

### ISSUE THREAD

**Issue by johncming** [miekg/dns#740] opened 2018-09-11 07:03 UTC
May be need a new function Join(labels ...string)

For example: 

```golang
    domain := "google.com"                                                          
    dns.Join("news", domain) // news.google.com. 
```

**Comment by tmthrgd** [comment] 2018-09-11 07:33
I’m going to close this as a duplicate of #525. Feel free to reopen if you disagree.

**Closed by tmthrgd** 2018-09-11 07:33 UTC
