### ISSUE TITLE
base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)

### ISSUE THREAD

**Issue by Luoyuanfeng** [miekg/dns#712] opened 2018-07-18 06:23 UTC
When I run `go build github.com/miekg/dns` command:

```
# github.com/miekg/dns
go/src/github.com/miekg/dns/msg_helpers.go:144: base32.HexEncoding.WithPadding undefined (type *base32.Encoding has no field or method WithPadding)
go/src/github.com/miekg/dns/msg_helpers.go:144: undefined: base32.NoPadding
```

**Comment by tmthrgd** [comment] 2018-07-18 08:18
This is a duplicate of #686, #687 and #701. You’ll have to upgrade to go 1.9 or 1.10.

**Closed by tmthrgd** 2018-07-18 08:18 UTC
