### ISSUE TITLE
ZoneParser error with "TSIG" records

### ISSUE THREAD

**Issue by lanrat** [miekg/dns#810] opened 2018-11-12 21:18 UTC
When using `dns.NewZoneParser()` on a zone file, I get the following error:

```
dns: unknown RR type: "TSIG" at line: 433:36
```
Line 433 of the zone file contains the following line:
```
monitor.reg.neustar.com. 0      ANY     TSIG    hmac-md5.sig-alg.reg.int. 1541638220 300 16 Cocdc1taK0N1SnSb4sohRQ== 4270 NOERROR 0
```

Is this a bug? For the purposes of my project I currently don't care about TSIG records, would it be possible to tell the parser to ignore records it does not support?

**Comment by miekg** [comment] 2018-11-12 21:50
[ Quoting <notifications@github.com> in "[miekg/dns] ZoneParser error with "..." ]
>When using `dns.NewZoneParser()` on a zone file, I get the following error:
>
>```
>dns: unknown RR type: "TSIG" at line: 433:36
>```
>Line 433 of the zone file contains the following line:
>```
>monitor.reg.neustar.com. 0      ANY     TSIG    hmac-md5.sig-alg.reg.int. 1541638220 300 16 Cocdc1taK0N1SnSb4sohRQ== 4270 NOERROR 0
>```
>
>Is this a bug? For the purposes of my project I currently don't care about TSIG records, would it be possible to tell the parser to ignore records it does not support?

TSIG records don't have a TEXT representation, so they can't be read in.
If you need this to somehow work, you need to use RFC 3597 represenation.

**Comment by lanrat** [comment] 2018-11-12 21:59
Unfortunately I'm not in control of the input zone file. It's being generated by Neustar with what looks like an AXFR from dig.

If they are not conforming to the spec is there another way to make this work? Or alternatively, would it be possible to allow the parser to continue after throwing a noncritical error, allowing the user to decide what errors are worth stopping on?

**Comment by miekg** [comment] 2018-11-13 07:30
[ Quoting <notifications@github.com> in "Re: [miekg/dns] ZoneParser error wi..." ]
>Unfortunately I'm not in control of the input zone file. It's being generated by Neustar with what looks like an AXFR from dig.

you're not getting a zonefile, your getting an axfr with a transaction signature 
attached. Those are 2 different things. TSIG has no meaning in a zone and 
doesn't have a text representation, so it errors.

>If they are not conforming to the spec is there another way to make this work? Or alternatively, would it be possible to allow the parser to continue after throwing a noncritical error, allowing the user to decide what errors are worth stopping on?

you need to strip the TSIG, just as you (probably) need to drop the second SOA, 
although the parser happily returns that second one.

/Miek

--
Miek Gieben

**Comment by lanrat** [comment] 2018-11-21 02:47
Would it be possible to get an option to allow your parser to skip over these entries or allow it to recover from the error? I don't see stripping records as a pre-processing step practical in my scenario. Wouldn't this pre-processing step would need its own parser, defeating the point?

 I'm currently using my own very hacky parser for the root zones files from https://czds.icann.org/ however I'd like to move to your more complete parser, but it throws errors like this on many of the zones files provided by ICANN's CZDS service.

To help provide another example of a record that errors and should be skipped from a root zone file:
```
dns: bad NAPTR Flags: "u" at line: 168993:61
```

```
blackberry-plugin.software.nic.tel.     86400   in      naptr   100 100 u E2U+web:http !^.*\$!http://dev.telnic.org/downloads/blackberry.html! .
```

If you think that allowing your zone file parser to recover from non-fatal errors makes sense. I'd be willing to take a look at it and submit a PR.

**Comment by miekg** [comment] 2018-11-21 07:55
[ Quoting <notifications@github.com> in "Re: [miekg/dns] ZoneParser error wi..." ]
>Would it be possible to get an option to allow your parser to skip over these entries or allow it to recover from the error? I don't see stripping records as a pre-processing step practical in my scenario. Wouldn't this pre-processing step would need its own parser, defeating the point?
>
> I'm currently using my own very hacky parser for the root zones files from https://czds.icann.org/ however I'd like to move to your more complete parser, but it throws errors like this on many of the zones files provided by ICANN's CZDS service.
>
>To help provide another example of a record that errors and should be skipped from a root zone file:
>```
>dns: bad NAPTR Flags: "u" at line: 168993:61
>```
>
>```
>blackberry-plugin.software.nic.tel.     86400   in      naptr   100 100 u E2U+web:http !^.*\$!http://dev.telnic.org/downloads/blackberry.html! .
>```

this is plain wrong:

   The Flags and Services and Regexp
   fields are all quoted <character-string>s.

https://tools.ietf.org/html/rfc2915#section-9. Those fields are not quoted so 
that is an error.

Ignoring unknown RRs may be an option, but sounds dangerous so I'm not a fan it 
doing that.

I don't know what ICANN is serving you, but it's certainly not well formed 
zones.


/Miek

--
Miek Gieben

**Comment by miekg** [comment] 2018-11-21 18:38
Twitter thread with ICANN going on. Seems bind does ignore this crap

**Comment by miekg** [comment] 2018-11-21 18:44
I'm not willing to implement the same.

You need to read it with bind and then write it out again to clean. Then
you can read it again using this library and process

**Comment by lanrat** [comment] 2018-11-21 19:02
> How many zone files are actually garbage here?

I'm running this parser over the 1222 of them I have now, I'll report back once it finishes. Most seem fine.

> Twitter thread with ICANN going on. Seems bind does ignore this crap

Can you link the thread?

> You need to read it with bind and then write it out again to clean. Then
> you can read it again using this library and process

I was hoping to not need to resort to that. Mostly for performance reasons. Parsing some of the larger zones; like com, take a while, and double parsing does not help. I'll experiment parsing with bind.

**Comment by miekg** [comment] 2018-11-21 19:07
I feel your pain. ICANN doesn't care about what gets uploaded, so your
problem lays there.

I hope the entire twitter thread is linkable, because it's getting out of
hand
I'm miekg@ on twitter

**Comment by miekg** [comment] 2018-11-21 19:09
https://twitter.com/miekg/status/1065153838926176256?s=19

**Comment by miekg** [comment] 2018-11-21 20:18
So Neustar doesn't know what a zonefile as, as does .tel. Anymore?

**Comment by marka63** [comment] 2018-11-21 20:30
Bind is looking for a qstring but will accept a plain string.  It emits a qstring.  The is actually consistent with Postel's be liberal with what you accept and conservative with what you generate principal.

TSIG also needs to have a presentation format defined. Humans have to read it and sometime tools have to post process it.

**Comment by miekg** [comment] 2018-11-21 20:38
[ Quoting <notifications@github.com> in "Re: [miekg/dns] ZoneParser error wi..." ]
>Bind is looking for a qstring but will accept a plain string.  It emits a qstring.  The is actually consistent with Postel's be liberal with what you accept and conservative with what you generate principal.

Sure, and now its offloadig the (liberal) decision to infect this library.

>TSIG also needs to have a presentation format defined. Humans have to read it and sometime tools have to post process it.

Also sure: but it hasn't today, so it's illegal, please use RFC 3597 syntax.

This issue is very good at highlighting which registries have absolutely no
clue what they are doing.

**Comment by edmonds** [comment] 2018-11-21 20:42
:+1: for this library parsing zone files, and not zone files and also text files that resemble zone files.

**Comment by lanrat** [comment] 2018-11-21 21:08
Just finished parsing the rest of the zone files with this library. Only BIZ, TEL, and US error.
US has the same error as BIZ and is also run by Neustar. So its not too bad.

**Comment by miekg** [comment] 2018-11-28 19:44
Without a TSIG presentation format this is WAI; we discarding invalid zone.

TSIG needs an RFC which will be trivial; so this is your change to engage in the IETF process :)

Meanwhile closing this as Works As Intended

**Closed by miekg** 2018-11-28 19:44 UTC
